### ISSUE TITLE
Download GSM geo faill 

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#3015]
I am trying to download geo dataset. my sample file look as follow 

`samplename,description,batch,phenotype
GSM900167,MDAH087_IgG_ChIP-Seq GSM900167,MDAH087,input
GSM900168,MDAH087_p53_ChIP-Seq GSM900168,MDAH087,chip`

`bcbio_prepare_samples.py --out merged --csv GSE36749.csv -t ipython -q cpuqueue -s lsf -n 2
`
but I get this error message 

```
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 92, in prepare_bcbio_samples
    return ipython.zip_args(apply(sample.prepare_bcbio_samples, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 80, in apply
    return object(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 395, in prepare_bcbio_samples
    out_file = query_gsm(sample['files'], sample['out_file'], sample['config'])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 48, in query_gsm
    gsm_info = _query_info("sra", ids[-1])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 30, in _query_info
    for line in out.split("RUN_SET")[1].split("RUN"):
```

thanks a lot! 
Alessandro

**Comment by mjsteinbaugh** [comment]
@apastore Do you have any more information from the error log? I'll see if I can reproduce this on my install. In the meantime, consider taking a look at sra-tools `prefetch` and `fasterq-dump` to pull down and split out the FASTQ files from SRA.

**Comment by naumenko-sa** [comment]
O2 bcbio users reported another SRA downloading issue:

example.csv:
```
samplename,description
GSM3508215,HEK293T
```

command
```
module load bcbio/latest sratoolkit/2.9.0
bcbio_prepare_samples.py --csv example.csv --out fastq
```

error
```
Traceback (most recent call last):
File "/n/app/bcbio/tools/bin/bcbio_prepare_samples.py", line 194, in <module>
samples = run_parallel("prepare_bcbio_samples", samples)
File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
return run_multicore(fn, items, config, parallel=parallel)
File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
if self.dispatch_one_batch(iterator):
File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
self._dispatch(tasks)
File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
job = self._backend.apply_async(batch, callback=cb)
File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
result = ImmediateResult(func)
File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__

self.results = batch()

File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__

for func, args, kwargs in self.items]

File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>

for func, args, kwargs in self.items]

File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper

return f(*args, **kwargs)

File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 108, in prepare_bcbio_samples

return sample.prepare_bcbio_samples(*args)

File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 398, in prepare_bcbio_samples
out_file = query_gsm(sample['files'], sample['out_file'], sample['config'])
File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 48, in query_gsm
gsm_info = _query_info("sra", ids[-1])
File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 30, in _query_info
for line in out.split("RUN_SET")[1].split("RUN"):
TypeError: a bytes-like object is required, not 'str'
```

Which had two components: python2/python3 bug and SRR syntax changed. ftp link is not working anymore, the alternative path is in the XML, addressed in 
https://github.com/bcbio/bcbio-nextgen/pull/3034

**Comment by naumenko-sa** [comment]
With that fix applied, I was able to download files from the original issue:

example1.csv:
```
samplename,description
GSM900167,MDAH087_IgG_ChIP-Seq
GSM900168,MDAH087_p53_ChIP-Seq
```

```
bcbio_prepare_samples.py --csv example1.csv --out fastq
```
Please not that I used one thread. 
@Rory I was not lucky with multi-threading here.

SN

**Comment by mjsteinbaugh** [comment]
We should replace `fastq-dump` with `fasterq-dump`, which natively supports multiple threads (see sra-tools documentation for details).

Relevant code is here: https://github.com/bcbio/bcbio-nextgen/blob/2bcb644c1bd061add6110d483af69f14850630bc/bcbio/pipeline/sra.py#L121

**Comment by rory** [comment]
@naumenko-sa wrong @rory 😃😉

**Comment by apastore** [comment]
Thanks a lot! I have update to the last version, but I still receive the same error. do you have any idea?

2019-12-14 09:52:37.987 [IPClusterStart] Using existing profile dir: '/lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython'
2019-12-14 09:52:37.987 [IPClusterStart] Searching path ['/lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176', '/lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython', '/home/pastore/data/bcbio/anaconda/etc/ipython', '/usr/local/etc/ipython', '/etc/ipython'] for config files
2019-12-14 09:52:37.988 [IPClusterStart] Attempting to load config file: ipython_config.py
2019-12-14 09:52:37.988 [IPClusterStart] Looking for ipython_config in /etc/ipython
2019-12-14 09:52:37.988 [IPClusterStart] Looking for ipython_config in /usr/local/etc/ipython
2019-12-14 09:52:37.988 [IPClusterStart] Looking for ipython_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2019-12-14 09:52:37.988 [IPClusterStart] Looking for ipython_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython
2019-12-14 09:52:37.989 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython/ipython_config.py
2019-12-14 09:52:37.989 [IPClusterStart] Looking for ipython_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176
2019-12-14 09:52:37.990 [IPClusterStart] Attempting to load config file: ipcluster_0a5e321a_09a9_427a_a2f6_cb7b08d02ec9_config.py
2019-12-14 09:52:37.990 [IPClusterStart] Looking for ipcontroller_config in /etc/ipython
2019-12-14 09:52:37.990 [IPClusterStart] Looking for ipcontroller_config in /usr/local/etc/ipython
2019-12-14 09:52:37.990 [IPClusterStart] Looking for ipcontroller_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2019-12-14 09:52:37.990 [IPClusterStart] Looking for ipcontroller_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython
2019-12-14 09:52:37.990 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython/ipcontroller_config.py
2019-12-14 09:52:37.991 [IPClusterStart] Looking for ipcontroller_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176
2019-12-14 09:52:37.991 [IPClusterStart] Attempting to load config file: ipcluster_0a5e321a_09a9_427a_a2f6_cb7b08d02ec9_config.py
2019-12-14 09:52:37.991 [IPClusterStart] Looking for ipengine_config in /etc/ipython
2019-12-14 09:52:37.992 [IPClusterStart] Looking for ipengine_config in /usr/local/etc/ipython
2019-12-14 09:52:37.992 [IPClusterStart] Looking for ipengine_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2019-12-14 09:52:37.992 [IPClusterStart] Looking for ipengine_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython
2019-12-14 09:52:37.992 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython/ipengine_config.py
2019-12-14 09:52:37.992 [IPClusterStart] Looking for ipengine_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176
2019-12-14 09:52:37.993 [IPClusterStart] Attempting to load config file: ipcluster_0a5e321a_09a9_427a_a2f6_cb7b08d02ec9_config.py
2019-12-14 09:52:37.993 [IPClusterStart] Looking for ipcluster_config in /etc/ipython
2019-12-14 09:52:37.993 [IPClusterStart] Looking for ipcluster_config in /usr/local/etc/ipython
2019-12-14 09:52:37.993 [IPClusterStart] Looking for ipcluster_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2019-12-14 09:52:37.993 [IPClusterStart] Looking for ipcluster_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython
2019-12-14 09:52:37.994 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython/ipcluster_config.py
2019-12-14 09:52:37.994 [IPClusterStart] Looking for ipcluster_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176
4 Engines running
[2019-12-14T14:53Z] lilac: Timing: prepare bcbio samples
[2019-12-14T14:53Z] lilac: ipython: prepare_bcbio_samples
[2019-12-14T14:53Z] ls11: Preparing p53_ChIP_MCF7 files ['GSM1429753'] to merge into /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/merged/p53_ChIP_MCF7.fastq.gz.
[2019-12-14T14:53Z] ls11: Preparing p53_ChIP_HCC70 files ['GSM1429756'] to merge into /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/merged/p53_ChIP_HCC70.fastq.gz.
[2019-12-14T14:53Z] ls11: Preparing p53_ChIP_MDA-MB-468 files ['GSM1429755'] to merge into /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/merged/p53_ChIP_MDA-MB-468.fastq.gz.
[2019-12-14T14:53Z] ls11: Preparing p53_ChIP_MDA-MB-175VII files ['GSM1429754'] to merge into /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/merged/p53_ChIP_MDA-MB-175VII.fastq.gz.
[2019-12-14T14:53Z] ls11: Get id sample for GSM1429753
[2019-12-14T14:53Z] ls11: Get id sample for GSM1429754
[2019-12-14T14:53Z] ls11: Get id sample for GSM1429756
[2019-12-14T14:53Z] ls11: Get id sample for GSM1429755
[2019-12-14T14:53Z] ls11: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 94, in prepare_bcbio_samples
    return ipython.zip_args(apply(sample.prepare_bcbio_samples, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 398, in prepare_bcbio_samples
    out_file = query_gsm(sample['files'], sample['out_file'], sample['config'])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 50, in query_gsm
    srrall = _query_info("sra", ids[-1])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 32, in _query_info
    for line in out.split("RUN_SET")[1].split("RUN")[1].split("SRAFile"):
IndexError: list index out of range
[2019-12-14T14:53Z] ls11: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 94, in prepare_bcbio_samples
    return ipython.zip_args(apply(sample.prepare_bcbio_samples, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 398, in prepare_bcbio_samples
    out_file = query_gsm(sample['files'], sample['out_file'], sample['config'])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 50, in query_gsm
    srrall = _query_info("sra", ids[-1])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 32, in _query_info
    for line in out.split("RUN_SET")[1].split("RUN")[1].split("SRAFile"):
IndexError: list index out of range
[2019-12-14T14:53Z] ls11: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 94, in prepare_bcbio_samples
    return ipython.zip_args(apply(sample.prepare_bcbio_samples, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 398, in prepare_bcbio_samples
    out_file = query_gsm(sample['files'], sample['out_file'], sample['config'])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 50, in query_gsm
    srrall = _query_info("sra", ids[-1])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 32, in _query_info
    for line in out.split("RUN_SET")[1].split("RUN")[1].split("SRAFile"):
IndexError: list index out of range
[2019-12-14T14:53Z] ls11: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 94, in prepare_bcbio_samples
    return ipython.zip_args(apply(sample.prepare_bcbio_samples, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 398, in prepare_bcbio_samples
    out_file = query_gsm(sample['files'], sample['out_file'], sample['config'])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 50, in query_gsm
    srrall = _query_info("sra", ids[-1])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 32, in _query_info
    for line in out.split("RUN_SET")[1].split("RUN")[1].split("SRAFile"):
IndexError: list index out of range
[2019-12-14T14:53Z] ls11: Preparing p53_ChIP_BT549 files ['GSM1429757'] to merge into /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/merged/p53_ChIP_BT549.fastq.gz.
[2019-12-14T14:53Z] ls11: Preparing H3K4me3_ChIP_MDA-MB-468_control_shRNA files ['GSM1429760'] to merge into /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/merged/H3K4me3_ChIP_MDA-MB-468_control_shRNA.fastq.gz.
[2019-12-14T14:53Z] ls11: Preparing H3_ChIP_MDA-MB-468_p53_shRNA files ['GSM1429759'] to merge into /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/merged/H3_ChIP_MDA-MB-468_p53_shRNA.fastq.gz.
[2019-12-14T14:53Z] ls11: Preparing H3_ChIP_MDA-MB-468_control_shRNA files ['GSM1429758'] to merge into /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/merged/H3_ChIP_MDA-MB-468_control_shRNA.fastq.gz.
[2019-12-14T14:53Z] ls11: Get id sample for GSM1429759
[2019-12-14T14:53Z] ls11: Get id sample for GSM1429757
[2019-12-14T14:53Z] ls11: Get id sample for GSM1429758
[2019-12-14T14:53Z] ls11: Get id sample for GSM1429760
[2019-12-14T14:53Z] ls11: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 94, in prepare_bcbio_samples
    return ipython.zip_args(apply(sample.prepare_bcbio_samples, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 398, in prepare_bcbio_samples
    out_file = query_gsm(sample['files'], sample['out_file'], sample['config'])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 50, in query_gsm
    srrall = _query_info("sra", ids[-1])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 32, in _query_info
    for line in out.split("RUN_SET")[1].split("RUN")[1].split("SRAFile"):
IndexError: list index out of range
[2019-12-14T14:53Z] ls11: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 94, in prepare_bcbio_samples
    return ipython.zip_args(apply(sample.prepare_bcbio_samples, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 398, in prepare_bcbio_samples
    out_file = query_gsm(sample['files'], sample['out_file'], sample['config'])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 50, in query_gsm
    srrall = _query_info("sra", ids[-1])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 32, in _query_info
    for line in out.split("RUN_SET")[1].split("RUN")[1].split("SRAFile"):
IndexError: list index out of range
[2019-12-14T14:53Z] ls11: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 94, in prepare_bcbio_samples
    return ipython.zip_args(apply(sample.prepare_bcbio_samples, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 398, in prepare_bcbio_samples
    out_file = query_gsm(sample['files'], sample['out_file'], sample['config'])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 50, in query_gsm
    srrall = _query_info("sra", ids[-1])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 32, in _query_info
    for line in out.split("RUN_SET")[1].split("RUN")[1].split("SRAFile"):
IndexError: list index out of range
[2019-12-14T14:53Z] ls11: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 94, in prepare_bcbio_samples
    return ipython.zip_args(apply(sample.prepare_bcbio_samples, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 398, in prepare_bcbio_samples
    out_file = query_gsm(sample['files'], sample['out_file'], sample['config'])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 50, in query_gsm
    srrall = _query_info("sra", ids[-1])
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sra.py", line 32, in _query_info
    for line in out.split("RUN_SET")[1].split("RUN")[1].split("SRAFile"):
IndexError: list index out of range
[2019-12-14T14:53Z] ls11: Preparing H3K4me3_ChIP_MDA-MB-468_p53_shRNA files ['GSM1429761'] to merge into /lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/merged/H3K4me3_ChIP_MDA-MB-468_p53_shRNA.fastq.gz.
[2019-12-14T14:53Z] ls11: Get id sample for GSM1429761
Sending a shutdown signal to the controller and engines.
2019-12-14 09:53:18.904 [IPClusterStop] Using existing profile dir: '/lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython'
2019-12-14 09:53:18.910 [IPClusterStop] Stopping cluster [pid=1645] with [signal=<Signals.SIGINT: 2>]
2019-12-14 09:53:19.619 [IPClusterStop] Using existing profile dir: '/lila/data/abdelwao-lab/pastorea/Project/aao/GSE59176/log/ipython'
2019-12-14 09:53:19.623 [IPClusterStop] Stopping cluster [pid=1645] with [signal=<Signals.SIGINT: 2>]
Traceback (most recent call last):
  File "/lila/home/pastore/data/bcbio_tool/bin/bcbio_prepare_samples.py", line 194, in <module>
    samples = run_parallel("prepare_bcbio_samples", samples)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipython.py", line 137, in run
    for data in view.map_sync(fn, items, track=False):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 344, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "</home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-140>", line 2, in map
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 52, in sync_results
    ret = f(self, *args, **kwargs)
  File "</home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-139>", line 2, in map
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 37, in save_ids
    ret = f(self, *args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 1114, in map
    return pf.map(*sequences)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 299, in map
    return self(*sequences, __ipp_mapping=True)
  File "</home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-122>", line 2, in __call__
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 80, in sync_view_results
    return f(self, *args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 285, in __call__
    return r.get()
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 169, in get
    raise self.exception()
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 228, in _resolve_result
    results = error.collect_exceptions(results, self._fname)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/error.py", line 233, in collect_exceptions
    raise e
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/error.py", line 231, in collect_exceptions
    raise CompositeError(msg, elist)
ipyparallel.error.CompositeError: one or more exceptions from call to method: prepare_bcbio_samples
[1:apply]: IndexError: list index out of range
[2:apply]: IndexError: list index out of range
[3:apply]: IndexError: list index out of range
[0:apply]: IndexError: list index out of range
.... 4 more exceptions ...

**Comment by apastore** [comment]
I have see that I can run 
bcbio_prepare_samples.py --out merged --csv GSE59176.csv

without error

**Comment by naumenko-sa** [comment]
Thanks @apastore for the following up! 
Glad, that the issue has been resolved for you. Let us know if you see any other issues!

So for now it is done as an issue, 
but will keep it open as a great suggestion from @mjsteinbaugh  to use fasterq-dump instead of fastq-dump.

SN

**Comment by naumenko-sa** [comment]
sratoolkit is evolving, supporting s3 downloads etc. 
we recommend using sratoolkit directly to retrieve fastq files.
