### ISSUE TITLE
error downloading gnomad files from ensembl

### ISSUE THREAD

**Issue by vdejager** [bcbio/bcbio-nextgen#3141]
There is an issue with downloading gnomad data:

in ggd-run.sh

url_prefix=http://ftp.ensemblorg.ebi.ac.uk/pub/data_files/homo_sapiens/GRCh37/variation_genotype/gnomad/r2.1/genomes/

the correct location of the file is:
http://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh37/variation_genotype/gnomad/r2.1/genomes/

**Version info**
 - bcbio version (bcbio_nextgen.py --version):
 - OS name and version: 1.2.0

**To Reproduce**
 - Exact bcbio command you have used
 - Your sample configuration file
bcbio_nextgen.py upgrade --datatarget gnomad

**Observed behavior**
Error message or bcbio output.
bcbio_nextgen.py upgrade --datatarget gnomad
Upgrading bcbio
Upgrading bcbio-nextgen data files
--2020-03-20 13:25:38--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2020-03-20 13:25:38--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 140.82.113.9
Connecting to codeload.github.com (codeload.github.com)|140.82.113.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ ........ ........ 1.14M
  3072K ........ ........ ........ .......                     829K=5.0s

2020-03-20 13:25:43 (1005 KB/s) - written to stdout [5189687]

List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'GRCh37', 'name': 'Human (GRCh37)', 'indexes': ['seq', 'twobit'], 'annotations': ['gnomad', 'GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'varpon', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'fusion-blacklist', 'mirbase'], 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4', 'giab-NA12878-NA24385-somatic', 'giab-NA24143', 'giab-NA24149', 'giab-NA24694', 'giab-NA24695']}], 'genome_indexes': ['bwa', 'star', 'rtg'], 'install_liftover': False, 'install_uniref': False}'): Human (GRCh37)
Running GGD recipe: GRCh37 gnomad 2.1
--2020-03-20 13:25:45--  https://gist.githubusercontent.com/naumenko-sa/d20db928b915a87bba4012ba1b89d924/raw/cf343b105cb3347e966cc95d049e364528c86880/gnomad_fields_to_keep.txt
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 151.101.36.133
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1938 (1.9K) [text/plain]
Saving to: ‘gnomad_fields_to_keep.txt’

gnomad_fields_to_keep.txt            100%[====================================================================>]   1.89K  --.-KB/s    in 0.001s  

2020-03-20 13:25:45 (2.16 MB/s) - ‘gnomad_fields_to_keep.txt’ saved [1938/1938]

--2020-03-20 13:25:45--  http://ftp.ensemblorg.ebi.ac.uk/pub/data_files/homo_sapiens/GRCh37/variation_genotype/gnomad/r2.1/genomes/gnomad.genomes.r2.1.sites.chr1_noVEP.vcf.gz
Resolving ftp.ensemblorg.ebi.ac.uk (ftp.ensemblorg.ebi.ac.uk)... failed: Name or service not known.
wget: unable to resolve host address ‘ftp.ensemblorg.ebi.ac.uk’
Traceback (most recent call last):
  File "/projects/xxxxxx/bcbio/1.2.0/tools/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/projects/xxxxxx/bcbio/1.2.0/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/projects/xxxxxx/bcbio/1.2.0/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 370, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/lustre5/xxxxxx/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/lustre5/xxxxxx/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/lustre5/xxxxxx/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/lustre5/0/xxxxxx/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)

  File "/lustre5/xxxxxx/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/projects/xxxxxx/bcbio/1.2.0/bcbio/anaconda/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/projects/xxxxxx/bcbio/1.2.0/bcbio/anaconda/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/lustre5/xxxxxx/bcbio/1.2.0/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 4.

**Expected behavior**
download and install of gnomad files
**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**

**Comment by naumenko-sa** [comment]
Hi @vdejager!

Thanks for reporting!
I've fixed it - please try again.

We probably also need to update this recipe to use a single vcf from Broad instead of chr vcfs from Ensembl:
https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/exomes/gnomad.exomes.r2.1.1.sites.vcf.bgz

Sergey

**Comment by matthdsm** [comment]
Also note Ensembl is currently moving datacenters, which hampers performance for all services.
See blog.ensembl.org.

Cheers
M

**Comment by vdejager** [comment]
Seems to work stable now, thanks

**Comment by vdejager** [comment]
today I got the same error trying to install the development branch on a fresh machine.
the error is still in https://github.com/chapmanb/cloudbiolinux/blob/f0eb952fd9301a73e88e55648357dbf2e0a970ea/ggd-recipes/hg19/gnomad.yaml#L23

**Comment by naumenko-sa** [comment]
Hi @vdejager!

I've fixed for GRCh37 not hg19, that is why. 
We have to fix hg19 as well, but for now the fastest option for you is to use GRCh37.
Would grch37  be an option for you - it is basically the same reference?

Sergey

**Comment by vdejager** [comment]
I was using GRCh37 indeed, but for downstream analysis my colleague requested hg19, so I thought to give it a try on the new infrastructure. I've reverted to GRCh37.

**Comment by naumenko-sa** [comment]
Hey @vdejager !

Sorry for the delay - it took so long :) 
I've fixed the recipe, please check out:
https://github.com/chapmanb/cloudbiolinux/pull/362

Some tips:
https://github.com/chapmanb/cloudbiolinux/blob/master/doc/hacking.md#testing-a-ggd-recipe

SN

**Comment by vdejager** [comment]
Thanks, I will test them this weekend.

**Comment by naumenko-sa** [comment]
Please let us know if the fix is not working for you!
