### ISSUE TITLE
New install: salmon can't launch

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#3446]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.7
- OS name and version (`lsb_release -ds`): Debian GNU/Linux 10 (buster)

**To Reproduce**
Exact bcbio command you have used:
```
$ /home/share/bcbio/anaconda/bin/salmon
/home/share/bcbio/anaconda/bin/salmon: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
```

**Observed behavior**
See above.

**Expected behavior**
Salmon should launch.

**Additional context**
This is a new, fresh install. `libtbb.so.2` is not provided anywhere, asf ar as I can see. There's a higher version available in the installation.

**Comment by naumenko-sa** [comment]
Hi @lbeltrame !

Thanks for reporting!

It works in our fresh installation:

```bash
$ bcbio_nextgen.py --version
1.2.7
$ which salmon
/path/to/anaconda/bin/salmon
$ salmon --version
salmon 1.4.0
$ conda list salmon
# packages in environment at /path/to/anaconda:
#
# Name                    Version                   Build  Channel
salmon                    1.4.0                hf69c8f4_0    bioconda
$ ldd `which salmon`
...
libtbb.so.2 => /path/to/anaconda/bin/../lib/libtbb.so.2 (0x00007f1bad7ed000)
...
```

Salmon is linked with a libtbb from conda, so it should not be a system-specific issue.

Could you try to reinstall salmon conda package 
```bash
conda remove salmon
conda install -c bioconda salmon
```

or even reinstall bcbio and bcbio tools?
(what if other packages were not installed successfully not just salmon?)

Recently a parallel issue of a broken conda installation was reported which was fixed by re-installing.

Sergey

**Comment by lbeltrame** [comment]
Would you be able to tell me from which conda package libtbb.so.2 comes from? I'd like to avoid reinstalling everything (removing and reinstalling salmon had no effect)

**Comment by naumenko-sa** [comment]
I think TBB is from https://github.com/conda-forge/tbb-feedstock,
see also Salmon page:
https://bioconda.github.io/recipes/salmon/README.html,
tbb is a requirement for Salmon

Not sure if you can remove TBB  - too many packages depend on that basic library.
Maybe force reinstall could help?
```
conda install -c conda-forge tbb --force-reinstall
```

SN

**Comment by roryk** [comment]
Hi everyone! There has been an issue with tbb, the new version of it breaks some of the scripts on bioconda (see https://www.biostars.org/p/494922/). This looks slightly different but I'm guessing tbb might need to be pinned anyway:

`mamba install --yes tbb=2020.2`

should do it. I'd try that if just reinstalling tbb doesn't fix the issue.

**Comment by lbeltrame** [comment]
Yes, it looks like that issue. Reinstalling tbb did not fix it, but pinning did. Thanks Rory!
