### ISSUE TITLE
No such file ‘HG002_SVs_Tier1_v0.6.vcf.gz’.

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3572]
I am getting a file not found error when attempting to install the genomes and aligners:

This is my upgrade command:
bcbio_nextgen.py upgrade -u skip --genomes GRCh37 --genomes hg38 --aligners bwa --aligners star

Seek your help in this matter please. Thank you.

```
--2021-12-06 23:56:50--  ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/HG002_SVs_Tier1_v0.6.vcf.gz
           => ‘validation/giab-NA24385/truth_sv.vcf.gz’
Resolving ftp-trace.ncbi.nlm.nih.gov (ftp-trace.ncbi.nlm.nih.gov)... 130.14.250.13, 130.14.250.11, 2607:f220:41e:250::13, ...
Connecting to ftp-trace.ncbi.nlm.nih.gov (ftp-trace.ncbi.nlm.nih.gov)|130.14.250.13|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6 ... done.
==> SIZE HG002_SVs_Tier1_v0.6.vcf.gz ... 25738211
==> PASV ... done.    ==> REST 42965056 ... done.
==> RETR HG002_SVs_Tier1_v0.6.vcf.gz ...
No such file ‘HG002_SVs_Tier1_v0.6.vcf.gz’.

Traceback (most recent call last):
  File "/apps/bcbio128/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 359, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/apps/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/apps/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/apps/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/apps/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/apps/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/apps/bcbio128/anaconda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/apps/bcbio128/anaconda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/apps/bcbio128/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 8.
```

**Comment by naumenko-sa** [comment]
Hi @gis-nlsim !

Thanks for catching this issues! ftp works for me as well, but, yes, we were trying to switch to https everywhere.
Please try again, it should be fixed in https://github.com/chapmanb/cloudbiolinux/commit/92dc23b1aa7420d4f8d5c39f47355be2a43f1ab4

(Make sure you are not using the cached copy of cloudbiolinux with the old recipe).

Sergey

**Comment by gis-nlsim** [comment]
Hi,
Now I’m encountering this issue:


2021-12-09 00:51:07 (51.8 MB/s) - â€˜canonical_cancer.txtâ€™ saved [704/704]

Updating hg38 genome resources configuration
Installing snpEff database GRCh37.75 in /apps/bcbio128/genomes/Hsapiens/GRCh37/snpeff
--2021-12-09 00:51:09--  http://downloads.sourceforge.net/project/snpeff/databases/v5_0/snpEff_v5_0_GRCh37.75.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-09 00:51:09 ERROR 404: Not Found.

Traceback (most recent call last):
  File "/apps/bcbio128/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 361, in upgrade_bcbio_data
    _upgrade_snpeff_data(galaxy_home, args, remotes)
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 439, in _upgrade_snpeff_data
    subprocess.check_call(["wget", "--no-check-certificate", "-c", "-O", dl_file, dl_url])
  File "/apps/bcbio128/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--no-check-certificate', '-c', '-O', 'snpEff_v5_0_GRCh37.75.zip', 'http://downloads.sourceforge.net/project/snpeff/databases/v5_0/snpEff_v5_0_GRCh37.75.zip']' returned non-zero exit status 8.
***@***.***:/apps/install.bcbio$

I don’t think it has anything to do with cloudbiolinux? Thanks

Regards,
N L Sim

**Comment by naumenko-sa** [comment]
yes, here you caught a snpeff update, see https://github.com/bcbio/bcbio-nextgen/issues/3570
you need to update bcbio code as well to fetch snpeff db from the microsoft cloud

**Comment by gis-nlsim** [comment]
Hi,
I'm still getting the following error.
1. I deleted the entire bcbio installation, and re-installed using
wget https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python3 bcbio_nextgen_install.py /apps/bcbio128 --tooldir=/apps/bcbio128 --nodata

For installation of Genomes, I used this command:
bcbio_nextgen.py upgrade -u development --genomes GRCh37 --genomes hg38 --aligners bwa --aligners star

This is the error I get:

2021-12-14 13:12:32 (4.71 MB/s) - ‘validation/giab-NA24695/truth_regions.bed’ saved [26092317/26092317]

Updating GRCh37 genome resources configuration
Updating hg38 genome resources configuration
Installing snpEff database GRCh37.75 in /apps/bcbio128/genomes/Hsapiens/GRCh37/snpeff
--2021-12-14 13:12:34--  http://downloads.sourceforge.net/project/snpeff/databases/v5_0/snpEff_v5_0_GRCh37.75.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-14 13:12:34 ERROR 404: Not Found.

Traceback (most recent call last):
  File "/apps/bcbio128/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    with bcbio_tmpdir():
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 361, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 439, in _upgrade_snpeff_data
    with utils.chdir(snpeff_base_dir):
  File "/apps/bcbio128/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--no-check-certificate', '-c', '-O', 'snpEff_v5_0_GRCh37.75.zip', 'http://downloads.sourceforge.net/project/snpeff/databases/v5_0/snpEff_v5_0_GRCh37.75.zip']' returned non-zero exit stat\us 8.

**Comment by naumenko-sa** [comment]
HI @gis-nlsim !

It seems that somehow you are calling the older bcbio. In bcbio1.2.9 snpeff database URL is different:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/install.py#L38

What is your:
```bash
snpEff -version
bcbio_nextgen.py --version
echo $PATH
which -a bcbio_nextgen.py
```

**Comment by gis-nlsim** [comment]
Thanks, it may be that when I wget the installation script, it was still pointing to the old bcbio? I’ve re-installed with all the steps and it’s installed successfully. 

Regards,
N L Sim

**Comment by naumenko-sa** [comment]
No, for the data installation you call bcbio_nextgen.py, not the installation script, i.e. the installed python package, which should point to the Azure cloud for snpeff. Likely, you still have two bcbio in your system and in the PATH.

I've just ran a GRCh37 installation after bcbio1.2.9 installation:

```bash
bcbio_nextgen.py upgrade -u skip --genomes GRCh37 --aligners bwa
```

It finished ok:
```
2021-12-17 00:47:04 (42.5 MB/s) - ‘validation/giab-NA24695/truth_regions.bed’ saved [14780609/14780609]

Updating GRCh37 genome resources configuration
Installing snpEff database GRCh37.75 in /path/to/install_test/genomes/Hsapiens/GRCh37/snpeff
--2021-12-17 00:47:05--  https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.75.zip
Resolving snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)... 52.239.234.228
Connecting to snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)|52.239.234.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 563180888 (537M) [application/zip]
Saving to: ‘snpEff_v5_0_GRCh37.75.zip’

snpEff_v5_0_GRCh37.75.zip                                   100%[=========================================================================================================================================>] 537.09M  5.11MB/s    in 2m 24s  

2021-12-17 00:49:30 (3.73 MB/s) - ‘snpEff_v5_0_GRCh37.75.zip’ saved [563180888/563180888]

Archive:  snpEff_v5_0_GRCh37.75.zip
  inflating: data/GRCh37.75/pwms.bin  
  inflating: data/GRCh37.75/sequence.1.bin  
  inflating: data/GRCh37.75/sequence.10.bin  
  inflating: data/GRCh37.75/sequence.11.bin  
  inflating: data/GRCh37.75/sequence.12.bin  
  inflating: data/GRCh37.75/sequence.13.bin  
  inflating: data/GRCh37.75/sequence.14.bin  
  inflating: data/GRCh37.75/sequence.15.bin  
  inflating: data/GRCh37.75/sequence.16.bin  
  inflating: data/GRCh37.75/sequence.17.bin  
  inflating: data/GRCh37.75/sequence.18.bin  
  inflating: data/GRCh37.75/sequence.19.bin  
  inflating: data/GRCh37.75/sequence.2.bin  
  inflating: data/GRCh37.75/sequence.20.bin  
  inflating: data/GRCh37.75/sequence.21.bin  
  inflating: data/GRCh37.75/sequence.22.bin  
  inflating: data/GRCh37.75/sequence.3.bin  
  inflating: data/GRCh37.75/sequence.4.bin  
  inflating: data/GRCh37.75/sequence.5.bin  
  inflating: data/GRCh37.75/sequence.6.bin  
  inflating: data/GRCh37.75/sequence.7.bin  
  inflating: data/GRCh37.75/sequence.8.bin  
  inflating: data/GRCh37.75/sequence.9.bin  
  inflating: data/GRCh37.75/sequence.HG1091_PATCH.bin  
  inflating: data/GRCh37.75/sequence.HG1257_PATCH.bin  
  inflating: data/GRCh37.75/sequence.HG1287_PATCH.bin  
  inflating: data/GRCh37.75/sequence.HG1424_PATCH.bin  
  inflating: data/GRCh37.75/sequence.HG1433_PATCH.bin  
  inflating: data/GRCh37.75/sequence.HG1436_HG1432_PATCH.bin  
  inflating: data/GRCh37.75/sequence.HG1459_PATCH.bin  
  inflating: data/GRCh37.75/sequence.HG1497_PATCH.bin  
  inflating: data/GRCh37.75/sequence.HG375_PATCH.bin  
  inflating: data/GRCh37.75/sequence.HSCHR5_1_CTG1.bin  
  inflating: data/GRCh37.75/sequence.HSCHR6_MHC_APD.bin  
  inflating: data/GRCh37.75/sequence.HSCHR6_MHC_COX.bin  
  inflating: data/GRCh37.75/sequence.HSCHR6_MHC_DBB.bin  
  inflating: data/GRCh37.75/sequence.HSCHR6_MHC_MANN.bin  
  inflating: data/GRCh37.75/sequence.HSCHR6_MHC_MCF.bin  
  inflating: data/GRCh37.75/sequence.HSCHR6_MHC_QBL.bin  
  inflating: data/GRCh37.75/sequence.HSCHR6_MHC_SSTO.bin  
  inflating: data/GRCh37.75/sequence.X.bin  
  inflating: data/GRCh37.75/sequence.Y.bin  
  inflating: data/GRCh37.75/sequence.bin  
  inflating: data/GRCh37.75/snpEffectPredictor.bin  
 extracting: data/GRCh37.75/cytoBand.txt.gz  
bcbio-nextgen data upgrade complete.
Upgrade completed successfully.
```
